"""v1.0.2

Revision ID: 8b2b8d5da503
Revises: 136f22d0b169
Create Date: 2024-07-28 21:44:58.528539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2b8d5da503'
down_revision: Union[str, None] = '136f22d0b169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'training', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'user_id')
    # ### end Alembic commands ###
